using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Selectors.Selections;
using DnDGen.CreatureGen.Tables;
using DnDGen.Infrastructure.Selectors.Collections;
using NUnit.Framework;
using System.Linq;

namespace DnDGen.CreatureGen.Tests.Integration.Tables.Creatures
{
    [TestFixture]
    internal class GendersTests : CollectionTests
    {
        protected override string TableName => TableNameConstants.Collection.Genders;

        private ICollectionDataSelector<CreatureDataSelection> creatureDataSelector;

        [SetUp]
        public void Setup()
        {
            creatureDataSelector = GetNewInstanceOf<ICollectionDataSelector<CreatureDataSelection>>();
        }

        [Test]
        public void GendersNames()
        {
            var creatures = CreatureConstants.GetAll();
            AssertCollectionNames(creatures);
        }

        [TestCase(CreatureConstants.Aasimar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Aboleth, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Achaierai, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Allip, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Androsphinx, GenderConstants.Male)]
        [TestCase(CreatureConstants.Angel_AstralDeva, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Angel_Planetar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Angel_Solar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ankheg, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Annis, GenderConstants.Female)]
        [TestCase(CreatureConstants.Ant_Giant_Queen, GenderConstants.Female)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ant_Giant_Worker, GenderConstants.Male)]
        [TestCase(CreatureConstants.Aranea, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Arrowhawk_Elder, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.AssassinVine, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Athach, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Avoral, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Azer, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Babau, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Balor, GenderConstants.Agender)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Barghest, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Barghest_Greater, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Basilisk, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Basilisk_Greater, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Bebilith, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Bee_Giant, GenderConstants.Male)]
        [TestCase(CreatureConstants.Behir, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Beholder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Beholder_Gauth, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Belker, GenderConstants.Agender)]
        [TestCase(CreatureConstants.BlinkDog, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Bodak, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.BoneDevil_Osyluth, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Bralani, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Bugbear, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Bulette, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.CarrionCrawler, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centaur, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.ChainDevil_Kyton, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.ChaosBeast, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Chimera_Black, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Chimera_Blue, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Chimera_Green, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Chimera_Red, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Chimera_White, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Choker, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Chuul, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cloaker, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Cockatrice,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Female)]
        [TestCase(CreatureConstants.Couatl, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Criosphinx, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_5Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_6Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_7Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_8Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_9Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_10Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_11Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Cryohydra_12Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Darkmantle, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Delver, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Derro, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Derro_Sane, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Destrachan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Devourer, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Digester, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.DisplacerBeast, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.DisplacerBeast_PackLord, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Djinni, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Djinni_Noble, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Doppelganger, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Dragonne, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.DragonTurtle, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Black_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Blue_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Brass_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Bronze_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Copper_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Gold_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Green_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_Silver_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Wyrmling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_VeryYoung, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Young, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Juvenile, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_YoungAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Adult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_MatureAdult, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Old, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_VeryOld, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Ancient, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_Wyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dragon_White_GreatWyrm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dretch, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Drider, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Dryad, GenderConstants.Female)]
        [TestCase(CreatureConstants.Dwarf_Deep, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dwarf_Duergar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dwarf_Hill, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Dwarf_Mountain, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Eagle_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Efreeti, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elemental_Air_Small, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Air_Medium, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Air_Large, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Air_Huge, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Air_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Air_Greater, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Small, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Medium, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Large, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Earth_Greater, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Small, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Medium, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Large, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Fire_Greater, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Small, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Medium, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Large, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Huge, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elemental_Water_Greater, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Elf_Aquatic, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_Drow, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_Gray, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_Half, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_High, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_Wild, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Elf_Wood, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Erinyes, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.EtherealFilcher, GenderConstants.Agender)]
        [TestCase(CreatureConstants.EtherealMarauder, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ettercap, GenderConstants.Female, GenderConstants.Male)] //https://www.dandwiki.com/wiki/Ettercap_(3.5e_Race)
        [TestCase(CreatureConstants.Ettin, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.FireBeetle_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.FormianMyrmarch, GenderConstants.Male)]
        [TestCase(CreatureConstants.FormianQueen, GenderConstants.Female)]
        [TestCase(CreatureConstants.FormianTaskmaster, GenderConstants.Male)]
        [TestCase(CreatureConstants.FormianWarrior, GenderConstants.Male)]
        [TestCase(CreatureConstants.FormianWorker, GenderConstants.Male)]
        [TestCase(CreatureConstants.FrostWorm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gargoyle, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Ghaele, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ghoul, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ghoul_Ghast, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ghoul_Lacedon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Cloud, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Fire, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Frost, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Hill, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Stone, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Stone_Elder, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Giant_Storm, GenderConstants.Female, GenderConstants.Male)] //https://forgottenrealms.fandom.com/wiki/Storm_giant
        [TestCase(CreatureConstants.GibberingMouther, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Girallon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Githyanki, GenderConstants.Female, GenderConstants.Male)] //https://forgottenrealms.fandom.com/wiki/Githyanki
        [TestCase(CreatureConstants.Githzerai, GenderConstants.Female, GenderConstants.Male)] //https://forgottenrealms.fandom.com/wiki/Githzerai
        [TestCase(CreatureConstants.Glabrezu, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Gnoll, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gnome_Forest, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gnome_Rock, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gnome_Svirfneblin, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Goblin, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gorgon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.GrayRender, GenderConstants.Agender)]
        [TestCase(CreatureConstants.GreenHag, GenderConstants.Female)]
        [TestCase(CreatureConstants.Grick, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Griffon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Grig, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Grig_WithFiddle, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Grimlock, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Gynosphinx, GenderConstants.Female)]
        [TestCase(CreatureConstants.Halfling_Deep, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Halfling_Lightfoot, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Halfling_Tallfellow, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Harpy, GenderConstants.Female, GenderConstants.Male)] //https://forgottenrealms.fandom.com/wiki/Harpy
        [TestCase(CreatureConstants.Hellcat_Bezekira, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.HellHound, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.HellHound_NessianWarhound, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hezrou, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Hieracosphinx, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hippogriff, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hobgoblin, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.HornedDevil_Cornugon, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Howler, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Human, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_5Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_6Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_7Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_8Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_9Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_10Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_11Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Hydra_12Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.IceDevil_Gelugon, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Imp, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.InvisibleStalker, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Janni, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Kobold, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Kraken, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Krenshar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.KuoToa, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Lamia, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Lammasu, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Lemure, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Leonal, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Lillend, GenderConstants.Female, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Lizardfolk, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Locathah, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Magmin, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Manticore, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Marilith, GenderConstants.Female)]
        [TestCase(CreatureConstants.Mephit_Air, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Dust, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Earth, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Fire, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Ice, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Magma, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Ooze, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Salt, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Steam, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mephit_Water, GenderConstants.Agender, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Merfolk, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mimic, GenderConstants.Agender)]
        [TestCase(CreatureConstants.MindFlayer, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Minotaur, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Mohrg, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Mummy, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Naga_Dark, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Naga_Guardian, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Naga_Spirit, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Naga_Water, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Nalfeshnee, GenderConstants.Agender)]
        [TestCase(CreatureConstants.NightHag, GenderConstants.Female)]
        [TestCase(CreatureConstants.Nightcrawler, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Nightwalker, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Nightwing, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Nightmare, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Nightmare_Cauchemar, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Nixie, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Nymph, GenderConstants.Female)]
        [TestCase(CreatureConstants.Ogre, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Ogre_Merrow, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.OgreMage, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Orc, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Orc_Half, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Otyugh, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.Owl_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Owlbear, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pegasus, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.PhantomFungus, GenderConstants.Agender)]
        [TestCase(CreatureConstants.PhaseSpider, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Phasm, GenderConstants.Agender)]
        [TestCase(CreatureConstants.PitFiend, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Pixie, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pixie_WithIrresistibleDance, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.PrayingMantis_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pseudodragon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.PurpleWorm, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_5Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_6Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_7Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_8Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_9Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_10Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_11Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Pyrohydra_12Heads, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Quasit, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Rakshasa, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Rast, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Ravid, GenderConstants.Agender)]
        [TestCase(CreatureConstants.RazorBoar, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Remorhaz, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Roper, GenderConstants.Hermaphrodite)]
        [TestCase(CreatureConstants.RustMonster, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Sahuagin, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Sahuagin_Malenti, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Sahuagin_Mutant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Salamander_Average, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Salamander_Flamebrother, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Salamander_Noble, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Satyr, GenderConstants.Male)]
        [TestCase(CreatureConstants.Satyr_WithPipes, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpionfolk, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Tiny, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.SeaCat, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.SeaHag, GenderConstants.Female)]
        [TestCase(CreatureConstants.Shadow, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Shadow_Greater, GenderConstants.Agender)]
        [TestCase(CreatureConstants.ShadowMastiff, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.ShamblingMound, GenderConstants.Agender)]
        [TestCase(CreatureConstants.ShockerLizard, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Shrieker, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Skum, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Slaad_Blue, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Slaad_Death, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Slaad_Gray, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Slaad_Green, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Slaad_Red, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Spectre, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.SpiderEater, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Colossal, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Gargantuan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Huge, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Large, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Medium, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Small, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Tiny, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Colossal, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Gargantuan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Huge, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Large, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Medium, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Small, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Tiny, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.StagBeetle_Giant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Stirge, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Succubus, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Tarrasque, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Tendriculos, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Thoqqua, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Tiefling, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Titan, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Tojanida_Adult, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Tojanida_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Tojanida_Juvenile, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Treant, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Triton, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Troglodyte, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Troll, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Troll_Scrag, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.TrumpetArchon, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.UmberHulk,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Female)]
        [TestCase(CreatureConstants.UmberHulk_TrulyHorrid,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Male,
            GenderConstants.Female)]
        [TestCase(CreatureConstants.Unicorn, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.VampireSpawn, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Vargouille, GenderConstants.Agender)]
        [TestCase(CreatureConstants.VioletFungus, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Vrock, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Wasp_Giant, GenderConstants.Male)]
        [TestCase(CreatureConstants.Wight, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.WillOWisp, GenderConstants.Agender)]
        [TestCase(CreatureConstants.WinterWolf, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Worg, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Wraith, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Wraith_Dread, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Wyvern, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.Xill, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Xorn_Average, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Xorn_Elder, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Xorn_Minor, GenderConstants.Agender)]
        [TestCase(CreatureConstants.YethHound, GenderConstants.Agender)]
        [TestCase(CreatureConstants.Yrthak, GenderConstants.Agender)]
        [TestCase(CreatureConstants.YuanTi_Abomination, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeArms, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeHead, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTail, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTailAndHumanLegs, GenderConstants.Female, GenderConstants.Male)]
        [TestCase(CreatureConstants.YuanTi_Pureblood, GenderConstants.Female, GenderConstants.Male)]
        public void Genders(string creature, params string[] genders)
        {
            AssertCollection(creature, genders);
        }

        [Test]
        public void MedusaAre99PercentFemale()
        {
            var genders = Enumerable.Repeat(GenderConstants.Female, 99).Concat([GenderConstants.Male]);
            Assert.That(genders.Count(), Is.EqualTo(100));
            Assert.That(genders.Count(g => g == GenderConstants.Female), Is.EqualTo(99));
            Assert.That(genders.Count(g => g == GenderConstants.Male), Is.EqualTo(1));

            AssertCollection(CreatureConstants.Medusa, [.. genders]);
        }

        [TestCase(CreatureConstants.Types.Construct)]
        [TestCase(CreatureConstants.Types.Ooze)]
        [TestCase(CreatureConstants.Types.Subtypes.Swarm)]
        public void CreaturesOfTypeAreAgender(string type)
        {
            var creatures = creatureDataSelector.SelectAllFrom(Config.Name, TableNameConstants.Collection.CreatureData)
                .Where(kvp => kvp.Value.Single().Types.Contains(type))
                .Select(kvp => kvp.Key);
            Assert.That(table.Keys, Is.SupersetOf(creatures));

            foreach (var creature in creatures)
            {
                AssertDistinctCollection(creature, GenderConstants.Agender);
            }
        }

        [Test]
        public void AnimalsAreMaleAndFemale()
        {
            //INFO: Swarms are agender and don't count as normal animals
            var animals = creatureDataSelector.SelectAllFrom(Config.Name, TableNameConstants.Collection.CreatureData)
                .Where(kvp => kvp.Value.Single().Types.Contains(CreatureConstants.Types.Animal)
                    && !kvp.Value.Single().Types.Contains(CreatureConstants.Types.Subtypes.Swarm))
                .Select(kvp => kvp.Key);
            Assert.That(table.Keys, Is.SupersetOf(animals));

            foreach (var creature in animals)
            {
                AssertDistinctCollection(creature, GenderConstants.Female, GenderConstants.Male);
            }
        }
    }
}
