using DnDGen.CreatureGen.Creatures;
using DnDGen.CreatureGen.Tables;
using NUnit.Framework;

namespace DnDGen.CreatureGen.Tests.Integration.Tables.Creatures
{
    [TestFixture]
    public class MaxAgeDescriptionsTests : CollectionTests
    {
        protected override string TableName => TableNameConstants.Collection.MaxAgeDescriptions;

        private const string Immortal = "Immortal";
        private const string NaturalCauses = "Will die of natural causes";
        private const string Swarm = "Swarm will disperse";
        private const string Unknown = "No known limit to lifespan";

        private const string Construct = CreatureConstants.Types.Construct;
        private const string Fey = CreatureConstants.Types.Fey;
        private const string Outsider = CreatureConstants.Types.Outsider;
        private const string Undead = CreatureConstants.Types.Undead;

        [Test]
        public void MaxAgeDescriptionsNames()
        {
            var creatures = CreatureConstants.GetAll();
            AssertCollectionNames(creatures);
        }

        [TestCase(CreatureConstants.Aasimar, NaturalCauses)]
        [TestCase(CreatureConstants.Aboleth, Immortal)]
        [TestCase(CreatureConstants.Achaierai, NaturalCauses)]
        [TestCase(CreatureConstants.Allip, Undead)]
        [TestCase(CreatureConstants.Androsphinx, Immortal)]
        [TestCase(CreatureConstants.Angel_AstralDeva, Outsider)]
        [TestCase(CreatureConstants.Angel_Planetar, Outsider)]
        [TestCase(CreatureConstants.Angel_Solar, Outsider)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs_Long, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs_Long_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs_Tall, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_MultipleLegs_Tall_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Colossal_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs_Long, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs_Long_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs_Tall, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_MultipleLegs_Tall_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Gargantuan_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs_Long, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs_Long_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs_Tall, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_MultipleLegs_Tall_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Huge_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs_Long, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs_Long_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs_Tall, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_MultipleLegs_Tall_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Large_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Medium_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Small_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Flexible, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_MultipleLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_MultipleLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Sheetlike, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_TwoLegs, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_TwoLegs_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Wheels_Wooden, Construct)]
        [TestCase(CreatureConstants.AnimatedObject_Tiny_Wooden, Construct)]
        [TestCase(CreatureConstants.Ankheg, NaturalCauses)]
        [TestCase(CreatureConstants.Annis, Unknown)]
        [TestCase(CreatureConstants.Ant_Giant_Queen, NaturalCauses)]
        [TestCase(CreatureConstants.Ant_Giant_Soldier, NaturalCauses)]
        [TestCase(CreatureConstants.Ant_Giant_Worker, NaturalCauses)]
        [TestCase(CreatureConstants.Ape, NaturalCauses)]
        [TestCase(CreatureConstants.Ape_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Aranea, NaturalCauses)]
        [TestCase(CreatureConstants.Arrowhawk_Adult, "Become Elder")]
        [TestCase(CreatureConstants.Arrowhawk_Elder, NaturalCauses)]
        [TestCase(CreatureConstants.Arrowhawk_Juvenile, "Become Adult")]
        [TestCase(CreatureConstants.AssassinVine, NaturalCauses)]
        [TestCase(CreatureConstants.Athach, NaturalCauses)]
        [TestCase(CreatureConstants.Avoral, NaturalCauses)]
        [TestCase(CreatureConstants.Azer, NaturalCauses)]
        [TestCase(CreatureConstants.Babau, Outsider)]
        [TestCase(CreatureConstants.Baboon, NaturalCauses)]
        [TestCase(CreatureConstants.Badger, NaturalCauses)]
        [TestCase(CreatureConstants.Badger_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Balor, Outsider)]
        [TestCase(CreatureConstants.BarbedDevil_Hamatula, Outsider)]
        [TestCase(CreatureConstants.Barghest, Unknown)]
        [TestCase(CreatureConstants.Barghest_Greater, Unknown)]
        [TestCase(CreatureConstants.Basilisk, NaturalCauses)]
        [TestCase(CreatureConstants.Basilisk_Greater, NaturalCauses)]
        [TestCase(CreatureConstants.Bat, NaturalCauses)]
        [TestCase(CreatureConstants.Bat_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bat_Swarm, Swarm)]
        [TestCase(CreatureConstants.Bear_Black, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Brown, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bear_Polar, NaturalCauses)]
        [TestCase(CreatureConstants.BeardedDevil_Barbazu, Outsider)]
        [TestCase(CreatureConstants.Bebilith, Outsider)]
        [TestCase(CreatureConstants.Bee_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Behir, NaturalCauses)]
        [TestCase(CreatureConstants.Beholder, NaturalCauses)]
        [TestCase(CreatureConstants.Beholder_Gauth, NaturalCauses)]
        [TestCase(CreatureConstants.Belker, Outsider)]
        [TestCase(CreatureConstants.Bison, NaturalCauses)]
        [TestCase(CreatureConstants.BlackPudding, "Become Elder")]
        [TestCase(CreatureConstants.BlackPudding_Elder, Unknown)]
        [TestCase(CreatureConstants.BlinkDog, NaturalCauses)]
        [TestCase(CreatureConstants.Boar, NaturalCauses)]
        [TestCase(CreatureConstants.Boar_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Bodak, Undead)]
        [TestCase(CreatureConstants.BombardierBeetle_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.BoneDevil_Osyluth, Outsider)]
        [TestCase(CreatureConstants.Bralani, NaturalCauses)]
        [TestCase(CreatureConstants.Bugbear, NaturalCauses)]
        [TestCase(CreatureConstants.Bulette, NaturalCauses)]
        [TestCase(CreatureConstants.Camel_Bactrian, NaturalCauses)]
        [TestCase(CreatureConstants.Camel_Dromedary, NaturalCauses)]
        [TestCase(CreatureConstants.CarrionCrawler, NaturalCauses)]
        [TestCase(CreatureConstants.Cat, NaturalCauses)]
        [TestCase(CreatureConstants.Centaur, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Colossal, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Gargantuan, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Monstrous_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Centipede_Swarm, Swarm)]
        [TestCase(CreatureConstants.ChainDevil_Kyton, Outsider)]
        [TestCase(CreatureConstants.ChaosBeast, Unknown)]
        [TestCase(CreatureConstants.Cheetah, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Black, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Blue, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Green, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_Red, NaturalCauses)]
        [TestCase(CreatureConstants.Chimera_White, NaturalCauses)]
        [TestCase(CreatureConstants.Choker, NaturalCauses)]
        [TestCase(CreatureConstants.Chuul, NaturalCauses)]
        [TestCase(CreatureConstants.Cloaker, NaturalCauses)]
        [TestCase(CreatureConstants.Cockatrice, NaturalCauses)]
        [TestCase(CreatureConstants.Couatl, Outsider)]
        [TestCase(CreatureConstants.Criosphinx, Immortal)]
        [TestCase(CreatureConstants.Crocodile, NaturalCauses)]
        [TestCase(CreatureConstants.Crocodile_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Cryohydra_10Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_11Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_12Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_5Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_6Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_7Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_8Heads, Unknown)]
        [TestCase(CreatureConstants.Cryohydra_9Heads, Unknown)]
        [TestCase(CreatureConstants.Darkmantle, NaturalCauses)]
        [TestCase(CreatureConstants.Deinonychus, NaturalCauses)]
        [TestCase(CreatureConstants.Delver, NaturalCauses)]
        [TestCase(CreatureConstants.Derro, NaturalCauses)]
        [TestCase(CreatureConstants.Derro_Sane, NaturalCauses)]
        [TestCase(CreatureConstants.Destrachan, NaturalCauses)]
        [TestCase(CreatureConstants.Devourer, Undead)]
        [TestCase(CreatureConstants.Digester, NaturalCauses)]
        [TestCase(CreatureConstants.DisplacerBeast, NaturalCauses)]
        [TestCase(CreatureConstants.DisplacerBeast_PackLord, NaturalCauses)]
        [TestCase(CreatureConstants.Djinni, Outsider)]
        [TestCase(CreatureConstants.Djinni_Noble, Outsider)]
        [TestCase(CreatureConstants.Dog, NaturalCauses)]
        [TestCase(CreatureConstants.Dog_Riding, NaturalCauses)]
        [TestCase(CreatureConstants.Donkey, NaturalCauses)]
        [TestCase(CreatureConstants.Doppelganger, NaturalCauses)]
        [TestCase(CreatureConstants.Dragon_Black_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Black_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Black_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Black_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Black_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Black_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Black_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Black_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Black_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Black_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Black_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Blue_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Blue_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Blue_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Blue_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Blue_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Blue_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Blue_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Blue_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Brass_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Brass_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Brass_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Brass_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Brass_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Brass_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Brass_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Brass_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Bronze_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Bronze_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Bronze_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Bronze_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Bronze_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Bronze_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Bronze_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Bronze_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Copper_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Copper_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Copper_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Copper_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Copper_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Copper_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Copper_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Copper_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Gold_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Gold_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Gold_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Gold_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Gold_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Gold_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Gold_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Gold_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Green_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Green_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Green_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Green_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Green_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Green_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Green_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Green_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Green_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Green_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Green_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Red_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Red_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Red_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Red_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Red_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Red_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Red_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Red_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Red_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Red_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Red_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_Silver_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_Silver_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_Silver_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_Silver_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_Silver_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_Silver_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_Silver_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_Silver_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.Dragon_White_Adult, "Become Mature Adult")]
        [TestCase(CreatureConstants.Dragon_White_Ancient, "Become Wyrm")]
        [TestCase(CreatureConstants.Dragon_White_GreatWyrm, "The Twilight")]
        [TestCase(CreatureConstants.Dragon_White_Juvenile, "Become Young Adult")]
        [TestCase(CreatureConstants.Dragon_White_MatureAdult, "Become Old")]
        [TestCase(CreatureConstants.Dragon_White_Old, "Become Very Old")]
        [TestCase(CreatureConstants.Dragon_White_VeryOld, "Become Ancient")]
        [TestCase(CreatureConstants.Dragon_White_VeryYoung, "Become Young")]
        [TestCase(CreatureConstants.Dragon_White_Wyrm, "Become Great Wyrm")]
        [TestCase(CreatureConstants.Dragon_White_Wyrmling, "Become Very Young")]
        [TestCase(CreatureConstants.Dragon_White_Young, "Become Juvenile")]
        [TestCase(CreatureConstants.Dragon_White_YoungAdult, "Become Adult")]
        [TestCase(CreatureConstants.DragonTurtle, NaturalCauses)]
        [TestCase(CreatureConstants.Dragonne, NaturalCauses)]
        [TestCase(CreatureConstants.Dretch, Outsider)]
        [TestCase(CreatureConstants.Drider, NaturalCauses)]
        [TestCase(CreatureConstants.Dryad, Fey)]
        [TestCase(CreatureConstants.Dwarf_Deep, NaturalCauses)]
        [TestCase(CreatureConstants.Dwarf_Duergar, NaturalCauses)]
        [TestCase(CreatureConstants.Dwarf_Hill, NaturalCauses)]
        [TestCase(CreatureConstants.Dwarf_Mountain, NaturalCauses)]
        [TestCase(CreatureConstants.Eagle, NaturalCauses)]
        [TestCase(CreatureConstants.Eagle_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Efreeti, Outsider)]
        [TestCase(CreatureConstants.Elasmosaurus, NaturalCauses)]
        [TestCase(CreatureConstants.Elemental_Air_Elder, Outsider)]
        [TestCase(CreatureConstants.Elemental_Air_Greater, Outsider)]
        [TestCase(CreatureConstants.Elemental_Air_Huge, Outsider)]
        [TestCase(CreatureConstants.Elemental_Air_Large, Outsider)]
        [TestCase(CreatureConstants.Elemental_Air_Medium, Outsider)]
        [TestCase(CreatureConstants.Elemental_Air_Small, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Elder, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Greater, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Huge, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Large, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Medium, Outsider)]
        [TestCase(CreatureConstants.Elemental_Earth_Small, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Elder, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Greater, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Huge, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Large, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Medium, Outsider)]
        [TestCase(CreatureConstants.Elemental_Fire_Small, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Elder, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Greater, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Huge, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Large, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Medium, Outsider)]
        [TestCase(CreatureConstants.Elemental_Water_Small, Outsider)]
        [TestCase(CreatureConstants.Elephant, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Aquatic, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Drow, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Gray, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Half, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_High, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Wild, NaturalCauses)]
        [TestCase(CreatureConstants.Elf_Wood, NaturalCauses)]
        [TestCase(CreatureConstants.Erinyes, Outsider)]
        [TestCase(CreatureConstants.EtherealFilcher, NaturalCauses)]
        [TestCase(CreatureConstants.EtherealMarauder, NaturalCauses)]
        [TestCase(CreatureConstants.Ettercap, NaturalCauses)]
        [TestCase(CreatureConstants.Ettin, NaturalCauses)]
        [TestCase(CreatureConstants.FireBeetle_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.FormianMyrmarch, NaturalCauses)]
        [TestCase(CreatureConstants.FormianQueen, NaturalCauses)]
        [TestCase(CreatureConstants.FormianTaskmaster, NaturalCauses)]
        [TestCase(CreatureConstants.FormianWarrior, NaturalCauses)]
        [TestCase(CreatureConstants.FormianWorker, NaturalCauses)]
        [TestCase(CreatureConstants.FrostWorm, NaturalCauses)]
        [TestCase(CreatureConstants.Gargoyle, "Crumbles to dust")]
        [TestCase(CreatureConstants.Gargoyle_Kapoacinth, "Crumbles to dust")]
        [TestCase(CreatureConstants.GelatinousCube, Immortal)]
        [TestCase(CreatureConstants.Ghaele, NaturalCauses)]
        [TestCase(CreatureConstants.Ghoul, Undead)]
        [TestCase(CreatureConstants.Ghoul_Ghast, Undead)]
        [TestCase(CreatureConstants.Ghoul_Lacedon, Undead)]
        [TestCase(CreatureConstants.Giant_Cloud, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Fire, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Frost, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Hill, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Stone, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Stone_Elder, NaturalCauses)]
        [TestCase(CreatureConstants.Giant_Storm, NaturalCauses)]
        [TestCase(CreatureConstants.GibberingMouther, Immortal)]
        [TestCase(CreatureConstants.Girallon, NaturalCauses)]
        [TestCase(CreatureConstants.Githyanki, NaturalCauses)]
        [TestCase(CreatureConstants.Githzerai, NaturalCauses)]
        [TestCase(CreatureConstants.Glabrezu, Outsider)]
        [TestCase(CreatureConstants.Gnoll, NaturalCauses)]
        [TestCase(CreatureConstants.Gnome_Forest, NaturalCauses)]
        [TestCase(CreatureConstants.Gnome_Rock, NaturalCauses)]
        [TestCase(CreatureConstants.Gnome_Svirfneblin, NaturalCauses)]
        [TestCase(CreatureConstants.Goblin, NaturalCauses)]
        [TestCase(CreatureConstants.Golem_Clay, Construct)]
        [TestCase(CreatureConstants.Golem_Flesh, Construct)]
        [TestCase(CreatureConstants.Golem_Iron, Construct)]
        [TestCase(CreatureConstants.Golem_Stone, Construct)]
        [TestCase(CreatureConstants.Golem_Stone_Greater, Construct)]
        [TestCase(CreatureConstants.Gorgon, NaturalCauses)]
        [TestCase(CreatureConstants.GrayOoze, Immortal)]
        [TestCase(CreatureConstants.GrayRender, NaturalCauses)]
        [TestCase(CreatureConstants.GreenHag, Unknown)]
        [TestCase(CreatureConstants.Grick, NaturalCauses)]
        [TestCase(CreatureConstants.Griffon, NaturalCauses)]
        [TestCase(CreatureConstants.Grig, NaturalCauses)]
        [TestCase(CreatureConstants.Grig_WithFiddle, NaturalCauses)]
        [TestCase(CreatureConstants.Grimlock, NaturalCauses)]
        [TestCase(CreatureConstants.Gynosphinx, Immortal)]
        [TestCase(CreatureConstants.Halfling_Deep, NaturalCauses)]
        [TestCase(CreatureConstants.Halfling_Lightfoot, NaturalCauses)]
        [TestCase(CreatureConstants.Halfling_Tallfellow, NaturalCauses)]
        [TestCase(CreatureConstants.Harpy, NaturalCauses)]
        [TestCase(CreatureConstants.Hawk, NaturalCauses)]
        [TestCase(CreatureConstants.HellHound, Outsider)]
        [TestCase(CreatureConstants.HellHound_NessianWarhound, Outsider)]
        [TestCase(CreatureConstants.Hellcat_Bezekira, Outsider)]
        [TestCase(CreatureConstants.Hellwasp_Swarm, Swarm)]
        [TestCase(CreatureConstants.Hezrou, Outsider)]
        [TestCase(CreatureConstants.Hieracosphinx, Immortal)]
        [TestCase(CreatureConstants.Hippogriff, NaturalCauses)]
        [TestCase(CreatureConstants.Hobgoblin, NaturalCauses)]
        [TestCase(CreatureConstants.Homunculus, Construct)]
        [TestCase(CreatureConstants.HornedDevil_Cornugon, Outsider)]
        [TestCase(CreatureConstants.Horse_Heavy, NaturalCauses)]
        [TestCase(CreatureConstants.Horse_Heavy_War, NaturalCauses)]
        [TestCase(CreatureConstants.Horse_Light, NaturalCauses)]
        [TestCase(CreatureConstants.Horse_Light_War, NaturalCauses)]
        [TestCase(CreatureConstants.HoundArchon, Outsider)]
        [TestCase(CreatureConstants.Howler, NaturalCauses)]
        [TestCase(CreatureConstants.Human, NaturalCauses)]
        [TestCase(CreatureConstants.Hydra_10Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_11Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_12Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_5Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_6Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_7Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_8Heads, Unknown)]
        [TestCase(CreatureConstants.Hydra_9Heads, Unknown)]
        [TestCase(CreatureConstants.Hyena, NaturalCauses)]
        [TestCase(CreatureConstants.IceDevil_Gelugon, Outsider)]
        [TestCase(CreatureConstants.Imp, Outsider)]
        [TestCase(CreatureConstants.InvisibleStalker, Outsider)]
        [TestCase(CreatureConstants.Janni, Outsider)]
        [TestCase(CreatureConstants.Kobold, NaturalCauses)]
        [TestCase(CreatureConstants.Kolyarut, Construct)]
        [TestCase(CreatureConstants.Kraken, Immortal)]
        [TestCase(CreatureConstants.Krenshar, NaturalCauses)]
        [TestCase(CreatureConstants.KuoToa, NaturalCauses)]
        [TestCase(CreatureConstants.Lamia, NaturalCauses)]
        [TestCase(CreatureConstants.Lammasu, NaturalCauses)]
        [TestCase(CreatureConstants.LanternArchon, Outsider)]
        [TestCase(CreatureConstants.Lemure, Outsider)]
        [TestCase(CreatureConstants.Leonal, Outsider)]
        [TestCase(CreatureConstants.Leopard, NaturalCauses)]
        [TestCase(CreatureConstants.Lillend, Outsider)]
        [TestCase(CreatureConstants.Lion, NaturalCauses)]
        [TestCase(CreatureConstants.Lion_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Lizard, NaturalCauses)]
        [TestCase(CreatureConstants.Lizardfolk, NaturalCauses)]
        [TestCase(CreatureConstants.Lizard_Monitor, NaturalCauses)]
        [TestCase(CreatureConstants.Locathah, NaturalCauses)]
        [TestCase(CreatureConstants.Locust_Swarm, Swarm)]
        [TestCase(CreatureConstants.Magmin, Outsider)]
        [TestCase(CreatureConstants.MantaRay, NaturalCauses)]
        [TestCase(CreatureConstants.Manticore, NaturalCauses)]
        [TestCase(CreatureConstants.Marilith, Outsider)]
        [TestCase(CreatureConstants.Marut, Outsider)]
        [TestCase(CreatureConstants.Medusa, Immortal)]
        [TestCase(CreatureConstants.Megaraptor, NaturalCauses)]
        [TestCase(CreatureConstants.Merfolk, NaturalCauses)]
        [TestCase(CreatureConstants.Mephit_Air, Outsider)]
        [TestCase(CreatureConstants.Mephit_Dust, Outsider)]
        [TestCase(CreatureConstants.Mephit_Earth, Outsider)]
        [TestCase(CreatureConstants.Mephit_Fire, Outsider)]
        [TestCase(CreatureConstants.Mephit_Ice, Outsider)]
        [TestCase(CreatureConstants.Mephit_Magma, Outsider)]
        [TestCase(CreatureConstants.Mephit_Ooze, Outsider)]
        [TestCase(CreatureConstants.Mephit_Salt, Outsider)]
        [TestCase(CreatureConstants.Mephit_Steam, Outsider)]
        [TestCase(CreatureConstants.Mephit_Water, Outsider)]
        [TestCase(CreatureConstants.Mimic, NaturalCauses)]
        [TestCase(CreatureConstants.MindFlayer, NaturalCauses)]
        [TestCase(CreatureConstants.Minotaur, NaturalCauses)]
        [TestCase(CreatureConstants.Mohrg, Undead)]
        [TestCase(CreatureConstants.Monkey, NaturalCauses)]
        [TestCase(CreatureConstants.Mule, NaturalCauses)]
        [TestCase(CreatureConstants.Mummy, Undead)]
        [TestCase(CreatureConstants.Naga_Dark, Immortal)]
        [TestCase(CreatureConstants.Naga_Guardian, Immortal)]
        [TestCase(CreatureConstants.Naga_Spirit, Immortal)]
        [TestCase(CreatureConstants.Naga_Water, Immortal)]
        [TestCase(CreatureConstants.Nalfeshnee, Outsider)]
        [TestCase(CreatureConstants.NightHag, Outsider)]
        [TestCase(CreatureConstants.Nightcrawler, Undead)]
        [TestCase(CreatureConstants.Nightmare, Outsider)]
        [TestCase(CreatureConstants.Nightmare_Cauchemar, Outsider)]
        [TestCase(CreatureConstants.Nightwalker, Undead)]
        [TestCase(CreatureConstants.Nightwing, Undead)]
        [TestCase(CreatureConstants.Nixie, NaturalCauses)]
        [TestCase(CreatureConstants.Nymph, Fey)]
        [TestCase(CreatureConstants.OchreJelly, Immortal)]
        [TestCase(CreatureConstants.Octopus, NaturalCauses)]
        [TestCase(CreatureConstants.Octopus_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Ogre, NaturalCauses)]
        [TestCase(CreatureConstants.Ogre_Merrow, NaturalCauses)]
        [TestCase(CreatureConstants.OgreMage, NaturalCauses)]
        [TestCase(CreatureConstants.Orc, NaturalCauses)]
        [TestCase(CreatureConstants.Orc_Half, NaturalCauses)]
        [TestCase(CreatureConstants.Otyugh, Immortal)]
        [TestCase(CreatureConstants.Owl, NaturalCauses)]
        [TestCase(CreatureConstants.Owl_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Owlbear, NaturalCauses)]
        [TestCase(CreatureConstants.Pegasus, NaturalCauses)]
        [TestCase(CreatureConstants.PhantomFungus, NaturalCauses)]
        [TestCase(CreatureConstants.PhaseSpider, NaturalCauses)]
        [TestCase(CreatureConstants.Phasm, NaturalCauses)]
        [TestCase(CreatureConstants.PitFiend, Outsider)]
        [TestCase(CreatureConstants.Pixie, NaturalCauses)]
        [TestCase(CreatureConstants.Pixie_WithIrresistibleDance, NaturalCauses)]
        [TestCase(CreatureConstants.Pony, NaturalCauses)]
        [TestCase(CreatureConstants.Pony_War, NaturalCauses)]
        [TestCase(CreatureConstants.Porpoise, NaturalCauses)]
        [TestCase(CreatureConstants.PrayingMantis_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Pseudodragon, NaturalCauses)]
        [TestCase(CreatureConstants.PurpleWorm, NaturalCauses)]
        [TestCase(CreatureConstants.Pyrohydra_10Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_11Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_12Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_5Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_6Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_7Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_8Heads, Unknown)]
        [TestCase(CreatureConstants.Pyrohydra_9Heads, Unknown)]
        [TestCase(CreatureConstants.Quasit, Outsider)]
        [TestCase(CreatureConstants.Rakshasa, Outsider)]
        [TestCase(CreatureConstants.Rast, Outsider)]
        [TestCase(CreatureConstants.Rat, NaturalCauses)]
        [TestCase(CreatureConstants.Rat_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Rat_Swarm, Swarm)]
        [TestCase(CreatureConstants.Raven, NaturalCauses)]
        [TestCase(CreatureConstants.Ravid, Outsider)]
        [TestCase(CreatureConstants.RazorBoar, NaturalCauses)]
        [TestCase(CreatureConstants.Remorhaz, NaturalCauses)]
        [TestCase(CreatureConstants.Retriever, Construct)]
        [TestCase(CreatureConstants.Rhinoceras, NaturalCauses)]
        [TestCase(CreatureConstants.Roc, NaturalCauses)]
        [TestCase(CreatureConstants.Roper, NaturalCauses)]
        [TestCase(CreatureConstants.RustMonster, NaturalCauses)]
        [TestCase(CreatureConstants.Sahuagin, NaturalCauses)]
        [TestCase(CreatureConstants.Sahuagin_Malenti, NaturalCauses)]
        [TestCase(CreatureConstants.Sahuagin_Mutant, NaturalCauses)]
        [TestCase(CreatureConstants.Salamander_Average, "Become Noble")]
        [TestCase(CreatureConstants.Salamander_Flamebrother, "Become Average")]
        [TestCase(CreatureConstants.Salamander_Noble, Outsider)]
        [TestCase(CreatureConstants.Satyr, NaturalCauses)]
        [TestCase(CreatureConstants.Satyr_WithPipes, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Colossal, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Gargantuan, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpion_Monstrous_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Scorpionfolk, NaturalCauses)]
        [TestCase(CreatureConstants.SeaCat, NaturalCauses)]
        [TestCase(CreatureConstants.SeaHag, Unknown)]
        [TestCase(CreatureConstants.Shadow, Undead)]
        [TestCase(CreatureConstants.Shadow_Greater, Undead)]
        [TestCase(CreatureConstants.ShadowMastiff, Outsider)]
        [TestCase(CreatureConstants.ShamblingMound, NaturalCauses)]
        [TestCase(CreatureConstants.Shark_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Shark_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Shark_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Shark_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.ShieldGuardian, Construct)]
        [TestCase(CreatureConstants.ShockerLizard, NaturalCauses)]
        [TestCase(CreatureConstants.Shrieker, NaturalCauses)]
        [TestCase(CreatureConstants.Skum, NaturalCauses)]
        [TestCase(CreatureConstants.Slaad_Blue, "Become Green")]
        [TestCase(CreatureConstants.Slaad_Death, Outsider)]
        [TestCase(CreatureConstants.Slaad_Gray, Outsider)]
        [TestCase(CreatureConstants.Slaad_Green, "Become Gray")]
        [TestCase(CreatureConstants.Slaad_Red, "Become Green")]
        [TestCase(CreatureConstants.Snake_Constrictor, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Constrictor_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Viper_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Viper_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Viper_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Viper_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Snake_Viper_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Spectre, Undead)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Colossal, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Gargantuan, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_Hunter_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Colossal, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Gargantuan, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Huge, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Large, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Medium, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Small, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Monstrous_WebSpinner_Tiny, NaturalCauses)]
        [TestCase(CreatureConstants.Spider_Swarm, Swarm)]
        [TestCase(CreatureConstants.SpiderEater, NaturalCauses)]
        [TestCase(CreatureConstants.Squid, NaturalCauses)]
        [TestCase(CreatureConstants.Squid_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.StagBeetle_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Stirge, NaturalCauses)]
        [TestCase(CreatureConstants.Succubus, Outsider)]
        [TestCase(CreatureConstants.Tarrasque, Immortal)]
        [TestCase(CreatureConstants.Tendriculos, NaturalCauses)]
        [TestCase(CreatureConstants.Thoqqua, NaturalCauses)]
        [TestCase(CreatureConstants.Tiefling, NaturalCauses)]
        [TestCase(CreatureConstants.Tiger, NaturalCauses)]
        [TestCase(CreatureConstants.Tiger_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Titan, Outsider)]
        [TestCase(CreatureConstants.Toad, NaturalCauses)]
        [TestCase(CreatureConstants.Tojanida_Adult, "Become Elder")]
        [TestCase(CreatureConstants.Tojanida_Elder, NaturalCauses)]
        [TestCase(CreatureConstants.Tojanida_Juvenile, "Become Adult")]
        [TestCase(CreatureConstants.Treant, NaturalCauses)]
        [TestCase(CreatureConstants.Triceratops, NaturalCauses)]
        [TestCase(CreatureConstants.Triton, NaturalCauses)]
        [TestCase(CreatureConstants.Troglodyte, NaturalCauses)]
        [TestCase(CreatureConstants.Troll, NaturalCauses)]
        [TestCase(CreatureConstants.Troll_Scrag, NaturalCauses)]
        [TestCase(CreatureConstants.TrumpetArchon, Outsider)]
        [TestCase(CreatureConstants.Tyrannosaurus, NaturalCauses)]
        [TestCase(CreatureConstants.UmberHulk, NaturalCauses)]
        [TestCase(CreatureConstants.UmberHulk_TrulyHorrid, NaturalCauses)]
        [TestCase(CreatureConstants.Unicorn, NaturalCauses)]
        [TestCase(CreatureConstants.VampireSpawn, Undead)]
        [TestCase(CreatureConstants.Vargouille, Outsider)]
        [TestCase(CreatureConstants.VioletFungus, NaturalCauses)]
        [TestCase(CreatureConstants.Vrock, Outsider)]
        [TestCase(CreatureConstants.Wasp_Giant, NaturalCauses)]
        [TestCase(CreatureConstants.Weasel, NaturalCauses)]
        [TestCase(CreatureConstants.Weasel_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Whale_Baleen, NaturalCauses)]
        [TestCase(CreatureConstants.Whale_Cachalot, NaturalCauses)]
        [TestCase(CreatureConstants.Whale_Orca, NaturalCauses)]
        [TestCase(CreatureConstants.Wight, Undead)]
        [TestCase(CreatureConstants.WillOWisp, Immortal)]
        [TestCase(CreatureConstants.WinterWolf, NaturalCauses)]
        [TestCase(CreatureConstants.Wolf, NaturalCauses)]
        [TestCase(CreatureConstants.Wolf_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Wolverine, NaturalCauses)]
        [TestCase(CreatureConstants.Wolverine_Dire, NaturalCauses)]
        [TestCase(CreatureConstants.Worg, NaturalCauses)]
        [TestCase(CreatureConstants.Wraith, Undead)]
        [TestCase(CreatureConstants.Wraith_Dread, Undead)]
        [TestCase(CreatureConstants.Wyvern, NaturalCauses)]
        [TestCase(CreatureConstants.Xill, Outsider)]
        [TestCase(CreatureConstants.Xorn_Average, "Become Elder")]
        [TestCase(CreatureConstants.Xorn_Elder, "Disintegrates into dust")]
        [TestCase(CreatureConstants.Xorn_Minor, "Become Average")]
        [TestCase(CreatureConstants.YethHound, Outsider)]
        [TestCase(CreatureConstants.Yrthak, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Abomination, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeArms, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeHead, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTail, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Halfblood_SnakeTailAndHumanLegs, NaturalCauses)]
        [TestCase(CreatureConstants.YuanTi_Pureblood, NaturalCauses)]
        [TestCase(CreatureConstants.Zelekhut, Construct)]
        public void MaxAgeDescription(string creature, string maxAgeDescription)
        {
            Assert.That(maxAgeDescription, Is.Not.Empty, creature);
            AssertDistinctCollection(creature, [maxAgeDescription]);
        }
    }
}
